# -*- coding: utf-8 -*-
"""MiniProject3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlIKu_Uwm4OYGN_RgIQ6SN9AEpk2RkbL
"""

import numpy as np
from scipy import linalg
import json

# Question 2: Working with the 3x3 matrix

A2 = np.array([[10, -7, 0],
               [-3, 2, 6],
               [5, -1, 5]], dtype=float)

print("\nMatrix for Questions 2.1, 2.2, 2.3:")
print("="*70)
print(A2)

# Question 2.1: LU Decomposition

print("\nQuestion 2.1: LU Decomposition")
print("="*70)

P, L, U = linalg.lu(A2)

print("\nL matrix (Lower triangular with 1's on diagonal):")
print(L)

print("\nU matrix (Upper triangular):")
print(U)

print("\nP matrix (Permutation matrix):")
print(P)

verification = P @ A2
reconstruction = L @ U
print("\nVerification (P @ A should equal L @ U):")
print("Max difference:", np.max(np.abs(verification - reconstruction)))

# Question 2.2: SVD - Singular Values

print("\nQuestion 2.2: SVD - Singular Values")
print("="*70)

U_svd, singular_values, Vt = np.linalg.svd(A2)

print("\nSingular values:")
for i, sv in enumerate(singular_values):
    print(f"σ{i+1} = {sv:.10f}")

print("\nU matrix (left singular vectors):")
print(U_svd)

print("\nV^T matrix (right singular vectors transposed):")
print(Vt)

Sigma = np.zeros_like(A2)
np.fill_diagonal(Sigma, singular_values)
reconstruction_svd = U_svd @ Sigma @ Vt
print("\nVerification (U @ Σ @ V^T should equal A):")
print("Max difference:", np.max(np.abs(A2 - reconstruction_svd)))

# Question 2.3: QR Decomposition

print("\nQuestion 2.3: QR Decomposition")
print("="*70)

Q, R = np.linalg.qr(A2)

print("\nQ matrix (Orthogonal matrix):")
print(Q)

print("\nR matrix (Upper triangular):")
print(R)

reconstruction_qr = Q @ R
print("\nVerification (Q @ R should equal A):")
print("Max difference:", np.max(np.abs(A2 - reconstruction_qr)))

identity_check = Q.T @ Q
print("\nVerification that Q is orthogonal (Q^T @ Q should equal I):")
print("Max difference from identity:", np.max(np.abs(identity_check - np.eye(3))))

# Question 3: Computing Singular Values with NumPy

print("\nQuestion 3: Computing Singular Values with NumPy")
print("="*70)

with open('SVD_dataset.json', 'r') as f:
    svd_dataset = json.load(f)

A3 = np.array(svd_dataset)

print("\nMatrix from SVD_dataset.json:")
print(A3)

print("\nComputing SVD using NumPy:")
U_np, singular_values_np, Vt_np = np.linalg.svd(A3)

print("\nNumPy's singular values:")
for i, sv in enumerate(singular_values_np):
    print(f"σ{i+1} = {sv:.10f}")

# Summary

print("\nSUMMARY OF RESULTS")
print("="*70)

print("\nQuestion 2.1: LU Decomposition (3x3 matrix)")
print(f"  Permutation needed: {not np.allclose(P, np.eye(3))}")
print("\n  L matrix:")
print(L)
print("\n  U matrix:")
print(U)
print("\n  P matrix:")
print(P)

print("\nQuestion 2.2: Singular Values (3x3 matrix)")
print("  Singular values:")
for i, sv in enumerate(singular_values):
    print(f"    σ{i+1} = {sv:.10f}")

print("\nQuestion 2.3: QR Decomposition (3x3 matrix)")
print("\n  Q matrix:")
print(Q)
print("\n  R matrix:")
print(R)

print("\nQuestion 3: Computing Singular Values (5x5 matrix)")
print("  NumPy's singular values:")
for i, sv in enumerate(singular_values_np):
    print(f"    σ{i+1} = {sv:.10f}")
print("\nManual computation shown on paper")